# -------------------------------
# 自动分段插件配置
# -------------------------------
# 触发分段的最小字符数（0=所有消息都分段）
split_threshold: 600

# 每个分段的字符长度（建议≥100）
segment_size: 600

# -------------------------------
# 高级设置（可选）
# -------------------------------
# 是否启用智能分段（避免拆分单词，需要代码支持）
smart_split: false

# 分段间的最小间隔（秒）
min_interval: 0.1